#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

IHLQ=ZOSPMI
IMLQ=DFSF20

members='IV3C101J IV3C105J'
for mem in ${members}; do
	jcl="${HLQ}.${MLQ}.INSTALIB(${mem})"
	./runjcl "${jcl}"
	rc=$?
	if [ $rc -gt 0 ]; then
		echo "Allocation job ${jcl} failed with $rc" >&2
		exit $rc
	fi
done

asm="${HLQ}.${MLQ}.INSTALIB(IV9C201T)"
jcl='/tmp/imsgen.jcl'

mvscmd --pgm=ASMA90 --syslib=${HLQ}.${MLQ}.SDFSMAC --sysin="${asm}" --sysprint=dummy --syslin="${jcl}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "IMSGEN Assemble failed. See /tmp for details" >&2
	exit $rc
fi

#
# Need to compress this dataset if doing repeated imsgen's
#
./dcompress ZOSPMT.DFSF20.TFORMAT
rc=$?
if [ $rc -gt 0 ]; then
	echo "Unable to compress ZOSPMT.DSF20.TFORMAT before IMSGEN" >&2
	exit $rc
fi

./runjcl "${jcl}"
rc=$?
if [ $rc -gt 4 ]; then  # MSF - Greg Vance is helping me with the warnings
	echo "IMSGEN job ${jcl} failed with $rc" >&2
	exit $rc
fi

members='IV3C202J IV3C203J IV3C301J IV3C302J IV3C401J'
for mem in ${members}; do
	jcl="${HLQ}.${MLQ}.INSTALIB(${mem})"
	./runjcl "${jcl}"
	rc=$?
	if [ $rc -gt 4 ]; then
		echo "Job ${jcl} failed with $rc" >&2
		exit $rc
	fi
done
