#!/bin/sh

. ./dynreg.fn 

function chkdtouch {
	dtouchparms=$*
	for parm in $*; do
		dataset="${parm}"
	done	
	echo "Allocate ${dataset}"
	drm -f "${dataset}"
	dtouch ${dtouchparms}
	if [ $? -gt 0 ]; then
		echo "Error allocating dataset: ${dataset}" >&2
		exit 16
	fi
}

hlq=ZOSPMT
mlq=DFSF20

datasets="${hlq}.${mlq}.QBLKS ${hlq}.${mlq}.SHMSG ${hlq}.${mlq}.LGMSG"
for dataset in ${datasets}; do
	chkdtouch -tseq ${dataset}
done

datasets="${hlq}.${mlq}.ACBLIBA ${hlq}.${mlq}.ACBLIBB ${hlq}.${mlq}.FORMATA ${hlq}.${mlq}.FORMATB"
for dataset in ${datasets}; do
	chkdtouch -tpds -ru -l0 -B6144 ${dataset}
done

datasets="${hlq}.${mlq}.MODBLKSA ${hlq}.${mlq}.MODBLKSB"
for dataset in ${datasets}; do
	chkdtouch -tpds -ru -l0 -B32760 ${dataset}
done

dataset="${hlq}.${mlq}.MODSTAT"
chkdtouch -tpds -rfb -l80 -B80 -s56664 ${dataset}

dataset="${hlq}.${mlq}.RDS"
chkdtouch -tseq -B4096 ${dataset}

apfllq="SDFSRESL MODBLKSA MODBLKSB SDXRRESL SDFSJLIB"
for llq in ${apfllq}; do
	dataset="${hlq}.${mlq}.${llq}"
	dynamicAPFRegister "ADD" "${dataset}"
	rc=$?
	if [ $rc -gt 0 ]; then
		exit $rc
	fi
done

imsppt="
                             /* IMS ONLINE CONTROL REGION            */
   PPT PGMNAME(DFSMVRC0)     /* PROGRAM NAME = DFSMVRC0              */
            CANCEL           /* PROGRAM CAN BE CANCELLED             */
            KEY(7)           /* PROTECT KEY ASSIGNED IS 7            */
            NOSWAP           /* PROGRAM IS NOT-SWAPPABLE             */
            NOPRIV           /* PROGRAM IS NOT PRIVILEGED            */
            SYST             /* PROGRAM IS A SYSTEM TASK             */
            DSI              /* DOES REQUIRE DATA SET INTEGRITY      */
            PASS             /* PASSWORD PROTECTION ACTIVE           */
            AFF(NONE)        /* NO CPU AFFINITY                      */

                             /* BPE - BASE PRIMITIVE ENVIRONMENT     */
   PPT PGMNAME(BPEINI00)     /* PROGRAM NAME = BPEINI00              */
            CANCEL           /* PROGRAM CAN BE CANCELLED             */
            KEY(7)           /* PROTECT KEY ASSIGNED IS 7            */
            NOSWAP           /* PROGRAM IS NOT-SWAPPABLE             */
            NOPRIV           /* PROGRAM IS NOT PRIVILEGED            */
            DSI              /* REQUIRES DATA SET INTEGRITY          */
            PASS             /* CANNOT BYPASS PASSWORD PROTECTION    */
            SYST             /* PROGRAM IS A SYSTEM TASK             */
            AFF(NONE)        /* NO CPU AFFINITY                      */

PPT PGMNAME(HWSHWS00)     /* PROGRAM NAME = HWSHWS00           */
         CANCEL           /* PROGRAM CAN BE CANCELED           */
         KEY(7)           /* PROTECT KEY ASSIGNED IS 7         */
         SWAP             /* PROGRAM IS SWAPPABLE              */
         NOPRIV           /* PROGRAM IS NOT PRIVILEGED         */
         DSI              /* REQUIRES DATA SET INTEGRITY       */
         PASS             /* CANNOT BYPASS PASSWORD PROTECTION */
         SYST             /* PROGRAM IS A SYSTEM TASK          */
         AFF(NONE)        /* NO CPU AFFINITY                   */
"

dynamicPPTRegister "ADD" "@@" "${imsppt}"
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi
	
