#!/bin/sh

#set -x

mydir='./'

lstds='ZOSPMI.VTAMLST' 
libds='ZOSPMI.VTAMLIB'

maclib="SYS1.MACLIB:SYS1.SISTMAC1"

ivpapli="${lstds}(IVPAPLI)"
ivpclt="${lstds}(IVPCLT)"
ivpcli="${lstds}(IVPCLI)"
atcconiv="${lstds}(ATCCONIV)"
atcstriv="${lstds}(ATCSTRIV)"

ivpmodtb="//'${libds}(IVPMODTB)'"
ivpmodtbsrc="${mydir}/ivpmodtb.s"
ivpintab="//'${libds}(IVPINTAB)'"
ivpintabsrc="${mydir}/ivpintab.s"
ivpusstb="//'${libds}(IVPUSSTB)'"
ivpusstbsrc="${mydir}/ivpusstb.s"
ivpvtamproc="${mydir}/ivpvtam.jcl"

#
#msf - add rc checks to all of this
#
./dcompress "${lstds}"
./dcompress "${libds}"

decho "IVPAPLI  VBUILD TYPE=APPL                                               
IVPAPLL1 APPL  AUTH=(PASS,ACQ,SPO),DLOGMOD=IMS,MODETAB=IVPMODTB,       X
               PRTCT=IVPPASS1,PARSESS=YES                              " ${ivpapli}

decho "IVPLCLT  LBUILD                                                         
T1301    LOCAL  CUADDR=301,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
T1302    LOCAL  CUADDR=302,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
T1303    LOCAL  CUADDR=303,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
T1304    LOCAL  CUADDR=304,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
T1305    LOCAL  CUADDR=305,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                         " ${ivpclt}

decho "IVPLCLI  LBUILD                                                         
PMASTER1 LOCAL CUADDR=311,TERM=3277,FEATUR2=(MODEL2),                  X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
USER1 LOCAL CUADDR=313,TERM=3277,FEATUR2=(MODEL2),                     X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
USER2 LOCAL CUADDR=314,TERM=3277,FEATUR2=(MODEL2),                     X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
DFSETO01  LOCAL CUADDR=315,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                          
DFSETO02  LOCAL CUADDR=316,TERM=3277,FEATUR2=(MODEL2),                 X
               DLOGMOD=D4B32XX3,USSTAB=IVPUSSTB,LOGTAB=IVPINTAB,       X
               ISTATUS=ACTIVE,MODETAB=IVPMODTB                         " ${ivpcli}

# 
# msf - clean this up, check rcs, use 'better' /tmp
#
tmpo="/tmp/$$.o"
as -I"${maclib}" -o"${tmpo}" "${ivpmodtbsrc}"
ld -o${ivpmodtb} "${tmpo}"

as -I"${maclib}" -o"${tmpo}" "${ivpintabsrc}"
ld -o${ivpintab} "${tmpo}"

as -I"${maclib}" -o"${tmpo}" "${ivpusstbsrc}"
ld -o${ivpusstb} "${tmpo}"

rm "${tmpo}"

decho "IVPLCLT,IVPAPLI,IVPLCLI " ${atcconiv}

decho " CONFIG=IV,                                                            X
 SSCPID=03,MAXSUBA=15,HOSTSA=3,                                        X
 SSCPNAME=M94SSCP,NETID=M94NET                                         " ${atcstriv}

#
# have to do this because dcp does not support './' as a path
#
data=`cat "${ivpvtamproc}"`
decho "${data}" "SYS1.PROCLIB(IVPVTAM)"
