#!/bin/sh
#
# Compress dataset
#
#set -x
if [ $# -eq 0 ]; then
	echo "Syntax: $0 <dataset>" >&2
	echo "  compresses <dataset> in place" >&2
	exit 4
fi
ds="$1"

out=`echo "  COPY OUTDD=SYSUT2,INDD=SYSUT1" | mvscmd --pgm=IEBCOPY --sysut1=${ds},old --sysut2=${ds},old --sysin=stdin --sysprint=stdout`
rc=$?
if [ $rc -gt 0 ]; then
	echo "Compress failed." >&2
	opercmd "display grs,res=(*,${ds})" 
	echo "${out}" >&2
fi
exit $rc
