#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

maxwait=10
jobs='IV3E201J:0 IV3E202J:0 IV3E203J:0 IV3E204J:0 IV3E206J:0 IV3E301J:0 IV3E302J:0 IV3E303J:0 IV3E305J:0'
ds="${HLQ}.${MLQ}.INSTALIB"
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
exit $rc
