#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

members='IV3E308J:0 IV3E309J:0 IV3E312J:0 IV3E313J:0 IV3E314J:0 IV3E315J:0 IV3E317J:0 IV3E318J:0 IV3E319J:0'
ds="${HLQ}.${MLQ}.INSTALIB"
./runjobs "${ds}" ${maxwait} ${members}
rc=$?

exit $rc 
