#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

ds="${HLQ}.${MLQ}.INSTALIB"
maxwait=10
jobs='IV3F101J:0 IV3F102J:0 IV3F103J:0 IV3F104J:0 IV3F106J:1'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

irlmjobid=`./runjob "${ds}(IV3F201J)" 5 0`
rc=$?
if [ $rc -ne 64 ]; then
	echo "Expected job IV3F201J to continue running but it completed with rc $rc" >&2
	exit $rc
fi

jobs='IV3F204J IV3F205J'
for job in ${jobs}; do
	./runjobandreply "${ds}(${job})" 5 0 "INSERT IS DONE, REPLY"
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Expected member ${job} to run and then finish after reply clean, but it stopped with rc:$rc" >&2
		exit $rc
	fi
done

jobs='IV3F206J IV3F207J'
for job in ${jobs}; do
	jobid=`./runjob "${ds}(${job})" 5 0`
	rc=$?
	if [ $rc -ne 64 ] && [ $rc -ne 0 ]; then
		echo "Job ${jobid} (member ${job}) should have completed with rc:0 or timed out, but finished with rc:$rc" >&2
		echo "${out}" >&2
		exit $rc
	fi
	# If this is the first time this job is run, it will be waiting for a reply
	# If it has run before, it will complete with an RC of 0
	status=`jls ${jobid} | awk ' { print $4; }'`
	if [ "$status" = 'AC' ]; then
		opercmd "\$C${jobid},DUMP"
	fi
done

jobs='IV3F209J:0 IV3F210J:0'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

jobs='IV3F211J IV3F212J'
for job in ${jobs}; do
	./runjobandreply "${ds}(${job})" 5 0 "INSERT IS DONE, REPLY"
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Expected job ${job} to run and then finish after reply clean, but it stopped with rc:$rc" >&2
		echo "${out}" >&2
		exit $rc
	fi
done

opercmd "P IVP15RL1"
#msf - add check here that CC of job is 0
echo "IRLM Job ${irlmjobid} stopped"

exit 0
