#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

ds="${HLQ}.${MLQ}.INSTALIB"
maxwait=10
jobs='IV3F101J:0 IV3F102J:0 IV3F103J:0 IV3F104J:0 IV3F106J:1'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

irlmjobid=`./startjob "${ds}(IV3F201J)" ${maxwait} 'DXR117I IRLM001 INITIALIZATION COMPLETE'`
rc=$?
if [ $rc -ne 0 ]; then
	echo "Unable to start job IV3F201J"
	exit $rc
fi

jobs='IV3F204J IV3F205J'
for job in ${jobs}; do
	./runjobandreply "${ds}(${job})" ${maxwait} 0 'INSERT IS DONE, REPLY'
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Expected member ${job} to run and then finish after reply clean, but it stopped with rc:$rc" >&2
		exit $rc
	fi
done

jobs='IV3F206J IV3F207J'
for job in ${jobs}; do
	jobid=`./startjob "${ds}(${job})" ${maxwait} 'INSERT IS DONE, REPLY'`
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Unable to start job ${ds}(${job})" >&2
		exit $rc
	fi
	# If this is the first time this job is run, it will be waiting for a reply
	# If it has run before, it will complete with an RC of 0
	status=`jls ${jobid} 2>/dev/null | awk ' { print $4; }'`
	if [ "$status" = 'AC' ]; then
		if [ ${verbose} ]; then
			opercmd "\$C${jobid},DUMP" 
		else 
			opercmd "\$C${jobid},DUMP" >/dev/null 2>/dev/null
		fi
	fi
done

jobs='IV3F209J:0 IV3F210J:0'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

jobs='IV3F211J IV3F212J'
for job in ${jobs}; do
	./runjobandreply "${ds}(${job})" 5 0 "INSERT IS DONE, REPLY"
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "Expected job ${job} to run and then finish after reply clean, but it stopped with rc:$rc" >&2
		exit $rc
	fi
done

if [ ${verbose} ]; then
	opercmd "P IVP15RL1"
	echo " IRLM Job ${irlmjobid} stopped"
else
	opercmd "P IVP15RL1" >/dev/null 2>/dev/null
fi
#msf - add check here that CC of job is 0

exit 0
