#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

ds="${HLQ}.${MLQ}.INSTALIB"
maxwait=10

jobs='IV3F301J:0 IV3F302J:0 IV3F303J:0 IV3F305J:0 IV3F401J'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

exit $rc 
