#!/bin/sh
HLQ=ZOSPMT
MLQ=DFSF20

ds="${HLQ}.${MLQ}.INSTALIB"
maxwait=10

jobs='IV3H101J:0 IV3H102J:0 IV3H103J:0 IV3H104J:4 IV3H105J:0'
./runjobs "${ds}" ${maxwait} ${jobs}
rc=$?
if [ $rc -gt 0 ]; then
	exit $rc
fi

if [ ${verbose} ]; then
	opercmd "DUMPDS CLEAR,DSN=ALL"
else
	opercmd "DUMPDS CLEAR,DSN=ALL" >/dev/null 2>/dev/null
fi

irlmjobid=`./startjob "${ds}(IV3H201J)" ${maxwait} 'DXR117I IRLM001 INITIALIZATION COMPLETE'`
rc=$?
if [ $rc -ne 0 ]; then
	echo "Unable to start job IV3H201J"
	exit $rc
fi
dbdcjobid=`./startjobandreply "${ds}(IV3H203J)" ${maxwait} '/NRE CHKPT 0 FORMAT ALL'`
rc=$?
if [ $rc -ne 0 ]; then
	echo "Unable to start job IV3H203J"
	exit $rc
fi

exit 0
