#!/bin/sh
#set -x
HLQ=ZOSPMT
MLQ=DFSF20

IHLQ=ZOSPMI
IMLQ=DFSF20

ivpds="USERMAC"
for ds in $ivpds; do
	drm -f "${IHLQ}.${IMLQ}.${ds}"
	dtouch "${IHLQ}.${IMLQ}.${ds}"
	if [ $? -gt 0 ]; then
		exit 16
	fi
done

jcl="${HLQ}.${MLQ}.INSTALIB(IV9C101J)"
./runjcl "${jcl}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "Allocation JCL ${jcl} failed with $rc" >&2
	exit $rc
fi

asm="${HLQ}.${MLQ}.INSTALIB(IV9C201T)"
jcl='/tmp/imsgen.jcl'

mvscmd --pgm=ASMA90 --syslib=${HLQ}.${MLQ}.SDFSMAC --sysin="${asm}" --sysprint=dummy --syslin="${jcl}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "IMSGEN Assemble failed. See /tmp for details" >&2
	exit $rc
fi

./runjcl "${jcl}"
rc=$?
if [ $rc -gt 0 ]; then
	echo "IMSGEN JCL ${jcl} failed with $rc" >&2
	exit $rc
fi
