#!/bin/sh
#set -x

function runJobAndReply {
	jcl=$1     
	maxwait=$2
	maxrc=$3
	shift 3
	msg=$*

	md=`./mdate`
	jobid=`./startjob "${jcl}" ${maxwait} "${msg}"`
	match=`pcon -s ${md} 2>/dev/null | awk -vjobid=$jobid '{ if ($6 == jobid) { print }}' | grep "${msg}"`
	reply=`echo ${match} | awk '{ print $8; }'`
	reply=${reply##*@}
	if [ "${reply}" != '' ]; then
		if [ ${verbose} ]; then
			opercmd "r ${reply}"
		else
			opercmd "r ${reply}" >/dev/null 2>/dev/null
		fi
	else
		echo "Reply string: ${msg} not found after starting job" >&2
	fi
	
	./jobstatus ${maxwait} ${jobid} "${jcl}"
	rc=$?
	if [ $rc -lt ${maxrc} ]; then
		rc=0
	fi
	return $?
}

runJobAndReply $* 
exit $?   
