#!/bin/sh
#set -x

function runJobAndReply {
	jcl="$1"     
	maxwait=$2
	maxrc=$3
	msg="$4"

	out=`./runjob "${jcl}" ${maxwait} ${maxrc} 2>&1 >/dev/null`
	rc=$?
	if [ $rc -ne 64 ]; then
		echo "Expected job to continue running but it completed with rc $rc" >&2
		return $rc
	fi
	#
	#msf - clean this up
	#
	jobid=`echo ${out} | awk '{ print $1; }'`
	out=`pcon -r | grep $jobid | grep "${msg}"`
	reply=`echo ${out} | awk '{ print $8; }'`
	reply=${reply##*@}
	opercmd "r ${reply}"

	if [ "${jcl#*/}" = "${jcl}" ]; then
		# Dataset - no slashes
		jcl="//'${jcl}'"
	fi

	currwait=0
	while [ true ]; do
		status=`jls 2>/dev/null ${jobid}`
		state=`echo ${status} | awk ' { print $4; }'`
		case "$state" in
		CC)
			rc=`echo ${status} | awk ' { print $5; }'`
			if [ $rc -gt ${maxrc} ]; then
				echo "JCL ${jcl}, job ${jobid} failed with rc: $rc" >&2
			else 
				rc=0
			fi
			return ${rc}
		;;
		ABEND*)
			echo "JCL ${jcl}, job ${jobid} ABENDED" >&2
			return 32
		;;
		JCLERR)
			echo "JCL ${jcl}, job ${jobid} has a JCL error" >&2
			return 32
		;;
		*)
			sleep 1
			currwait=$((currwait+1))
		esac
		if [ ${currwait} -gt ${maxwait} ]; then
			echo "${jobid} (JCL ${jcl}) timed out waiting to complete" >&2
			return 64 
		fi
	done
}

runJobAndReply $* 
exit $?   
