#!/bin/sh
opts=$1
if [ "${opts}" = '-v' ]; then
	export verbose=true
fi

steps="A* C* D* E* F* H*" 

for step in $steps; do
	echo ${step}
	./${step}
	rc=$?
	if [ $rc -ne 0 ]; then
		echo "${step} failed with $rc." >&2
		exit $rc
	fi
done
